import { Patient } from '../../core/models';

/**
 * Mock Patients
 */
export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    mrn: 'MRN001234',
    firstName: 'Robert',
    lastName: 'Wilson',
    dateOfBirth: new Date('1965-03-15'),
    gender: 'male',
    email: 'robert.wilson@email.com',
    phone: '555-1001',
    address: {
      street: '123 Main St',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62701',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Linda Wilson',
      relationship: 'Spouse',
      phone: '555-1002',
      email: 'linda.wilson@email.com',
    },
    allergies: [
      {
        id: 'allg-1',
        name: 'Penicillin',
        severity: 'severe',
        reaction: 'Anaphylaxis',
        recordedDate: new Date('2020-05-10'),
      },
      {
        id: 'allg-2',
        name: 'Shellfish',
        severity: 'moderate',
        reaction: 'Hives and throat swelling',
        recordedDate: new Date('2019-08-22'),
      },
    ],
    chronicConditions: [
      {
        id: 'cond-1',
        icdCode: 'E11.9',
        name: 'Type 2 Diabetes',
        diagnosisDate: new Date('2015-02-14'),
        status: 'active',
        notes: 'Well controlled with metformin',
      },
      {
        id: 'cond-2',
        icdCode: 'I10',
        name: 'Essential Hypertension',
        diagnosisDate: new Date('2018-06-20'),
        status: 'active',
        notes: 'On lisinopril 10mg daily',
      },
    ],
    insuranceInfo: {
      provider: 'Blue Cross Blue Shield',
      policyNumber: 'BC123456789',
      groupNumber: 'GRP789',
      effectiveDate: new Date('2023-01-01'),
      expirationDate: new Date('2024-12-31'),
      coverageType: 'commercial',
    },
    isActive: true,
    createdAt: new Date('2020-05-10'),
    updatedAt: new Date('2024-07-20'),
  },
  {
    id: 'pat-2',
    mrn: 'MRN001235',
    firstName: 'Jennifer',
    lastName: 'Taylor',
    dateOfBirth: new Date('1978-07-22'),
    gender: 'female',
    email: 'jennifer.taylor@email.com',
    phone: '555-1010',
    address: {
      street: '456 Oak Ave',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
    emergencyContact: {
      name: 'David Taylor',
      relationship: 'Brother',
      phone: '555-1011',
    },
    allergies: [
      {
        id: 'allg-3',
        name: 'Latex',
        severity: 'moderate',
        reaction: 'Contact dermatitis',
        recordedDate: new Date('2021-03-10'),
      },
    ],
    chronicConditions: [
      {
        id: 'cond-3',
        icdCode: 'J45.9',
        name: 'Asthma',
        diagnosisDate: new Date('2010-11-05'),
        status: 'active',
        notes: 'Controlled with inhaler',
      },
    ],
    insuranceInfo: {
      provider: 'Aetna',
      policyNumber: 'AE987654321',
      effectiveDate: new Date('2023-03-01'),
      coverageType: 'commercial',
    },
    isActive: true,
    createdAt: new Date('2021-03-10'),
    updatedAt: new Date('2024-07-18'),
  },
  {
    id: 'pat-3',
    mrn: 'MRN001236',
    firstName: 'James',
    lastName: 'Martinez',
    dateOfBirth: new Date('1955-11-30'),
    gender: 'male',
    email: 'james.martinez@email.com',
    phone: '555-1020',
    address: {
      street: '789 Elm Rd',
      city: 'Naperville',
      state: 'IL',
      zipCode: '60540',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Maria Martinez',
      relationship: 'Daughter',
      phone: '555-1021',
    },
    allergies: [],
    chronicConditions: [
      {
        id: 'cond-4',
        icdCode: 'I21.9',
        name: 'Myocardial Infarction',
        diagnosisDate: new Date('2022-08-15'),
        status: 'active',
        notes: 'Post-MI recovery, under cardiology care',
      },
      {
        id: 'cond-5',
        icdCode: 'I10',
        name: 'Essential Hypertension',
        diagnosisDate: new Date('2000-01-10'),
        status: 'active',
      },
    ],
    insuranceInfo: {
      provider: 'Medicare',
      policyNumber: 'MEDI123456',
      effectiveDate: new Date('2020-05-01'),
      coverageType: 'medicare',
    },
    isActive: true,
    createdAt: new Date('2022-08-15'),
    updatedAt: new Date('2024-07-19'),
  },
];
